name: Update lock file
on:
  schedule:
    - cron: '0 */12 * * *'
  jobs:
    update-lock-file:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4.1.6
        - uses: cachix/install-nix-action@V27
          with:
              nix_path: nixpkgs=channel:nixos-unstable
        - run: |
            nix flake update
            git config user.email Lumesque@users.noreply.github.com
            git config user.name  homemanager-config
            git add flake.lock
            git commit -m 'updating' | true
            git push -u origin main
